---
name: moderne-ingest

on:
  workflow_call:
    secrets:
      moderne_api_access_token:
        description: The Moderne API access token to use for pushing the generated ASTs.
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.moderne_api_access_token }}
